name: json_serializable_fic
description: Adding support for fast immutable collections for json_serializable
version: 1.1.3
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dev_dependencies:
  test: ^1.16.8
  collection: "^1.15.0"
  fast_immutable_collections: ^11.1.0
  lints: ^6.0.0

dependencies:
  json_serializable: ^6.11.4
  json_annotation: ^4.3.0
  build_runner: ^2.4.15
  source_gen: ^4.2.0
  analyzer: ^10.0.1
  build: ^4.0.4
  json_serializable_fic_typehelpers: ^2.2.1
