name: json_serializable_immutable_collections
description: Adding support for immutable collections for json_serializable
version: 0.10.2
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  built_collection: ^5.0.0
  kt_dart: ^0.9.0
  lints: ^2.0.0

dependencies:
  json_serializable:  ^6.0.1
  json_annotation:  ^4.3.0
  build_runner: ^2.0.4
  source_gen: ^1.0.0
  analyzer: '>=3.0.0 <6.0.0'
  build: ^2.0.0
  json_serializable_kt_typehelpers: ^3.1.1
  json_serializable_built_typehelpers: ^3.1.1
