name: json_serializable_immutable_collections
description: Adding support for immutable collections for json_serializable
version: 1.1.2
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dev_dependencies:
  test: ^1.16.8
  built_collection: ^5.0.0
  kt_dart: ^1.1.0
  lints: ^5.1.1

dependencies:
  json_serializable: ^6.9.4
  json_annotation: ^4.3.0
  build_runner: ^2.4.15
  source_gen: ^4.2.0
  analyzer: ^10.0.1
  build: ^4.0.4
  json_serializable_kt_typehelpers: ^4.1.2
  json_serializable_built_typehelpers: ^4.1.2
