name: json_serializable_kt_typehelpers
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  kt_dart: ^0.9.0
  json_serializable: ^4.1.0
  json_serializable_type_helper_utils:
    path: ../json_serializable_type_helper_utils
  source_gen: ^1.0.0

dev_dependencies:
   test: any