name: json_serializable_built_typehelpers
description: typehelpers for built_collection, used for json_serializable.
version: 4.1.2
homepage: https://github.com/knaeckeKami/json_serializable_immutable_collections/tree/master/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  built_collection: ^5.0.0
  json_serializable_type_helper_utils: ^6.0.2
  source_gen: ^4.2.0
  analyzer: ^10.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.14.4
