name: json_serializable_mobx
description: Adding support for mobx collections for json_serializable
version: 1.1.1
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.16.8
  mobx: ^2.5.0
  lints: ^5.1.1

dependencies:
  json_serializable: ^6.9.4
  json_annotation: ^4.3.0
  build_runner: ^2.4.15
  analyzer: ^10.0.1
  source_gen: ^4.2.0
  build: ^4.0.4
  json_serializable_mobx_typehelpers: ^4.0.0
