name: combine_example
description: Example application on how to combine multiple typehelper packages
# version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.14.4
  json_serializable_built_typehelpers:
    path: ../typehelpers/json_serializable_built_typehelpers
  json_serializable_kt_typehelpers:
    path: ../typehelpers/json_serializable_kt_typehelpers
  json_serializable_fic_typehelpers:
    path: ../typehelpers/json_serializable_fic_typehelpers
  json_serializable_mobx_typehelpers:
    path: ../typehelpers/json_serializable_mobx_typehelpers
  json_serializable: ^6.0.1
  build_runner: ^2.0.0
